object VersionsCode{

    val appCompatVersion = "1.2.0"
    val coreVersion = "1.3.2"
    val constraintLayoutVersion = "2.0.4"
    val junitVersion = "4.13.1"
    val junitExtversion = "1.1.2"
    val espressoVersion = "3.3.0"
    val androidTestVersion = "1.3.0"
    val espressoContribVersion = "3.3.0"
    val androidXTestVersion = "1.2.0"
    val mockitoKotlinVersion = "2.2.0"
    val androidCoreTestVersion = "2.1.0"
    val idleResourceVersion = "3.2.0"
    val mockitoVersion = "3.6.0"
    val retrofit_version = "2.9.0"
    val logging_interceptor_version = "4.8.0"
    val kotlin_coroutines_version = "1.3.9"
    val lifecycle_version = "2.2.0"

    val materialVersion = "1.2.1"
    val recyclerViewVersion = "1.1.0"
    val glideVersion = "4.11.0"
    val cardViewVersion = "1.0.0"
    val sdpVersion = "1.0.6"
    val mockitoCoreVersion = "3.6.0"
    val mockitoInlineVersion = "3.6.0"
    val navigationFragmentVersion = "2.3.4"
    val navigationUiVersion = "2.3.4"
}